class Numbers {
  int numbers;
  bool? onSelected;

  Numbers({required this.numbers, this.onSelected});

  static List<Numbers> numbersOneToTen = [
    Numbers(numbers: 1),
    Numbers(numbers: 2),
    Numbers(numbers: 3),
    Numbers(numbers: 4),
    Numbers(numbers: 5),
    Numbers(numbers: 6),
    Numbers(numbers: 7),
    Numbers(numbers: 8),
    Numbers(numbers: 9),
    Numbers(numbers: 10),
  ];

  static List<Numbers> numbersOneToFifty = [
    Numbers(numbers: 1),
    Numbers(numbers: 2),
    Numbers(numbers: 3),
    Numbers(numbers: 4),
    Numbers(numbers: 5),
    Numbers(numbers: 6),
    Numbers(numbers: 7),
    Numbers(numbers: 8),
    Numbers(numbers: 9),
    Numbers(numbers: 10),
    Numbers(numbers: 11),
    Numbers(numbers: 12),
    Numbers(numbers: 13),
    Numbers(numbers: 14),
    Numbers(numbers: 15),
    Numbers(numbers: 16),
    Numbers(numbers: 17),
    Numbers(numbers: 18),
    Numbers(numbers: 19),
    Numbers(numbers: 20),
    Numbers(numbers: 21),
    Numbers(numbers: 22),
    Numbers(numbers: 23),
    Numbers(numbers: 24),
    Numbers(numbers: 25),
    Numbers(numbers: 26),
    Numbers(numbers: 27),
    Numbers(numbers: 28),
    Numbers(numbers: 29),
    Numbers(numbers: 30),
    Numbers(numbers: 31),
    Numbers(numbers: 32),
    Numbers(numbers: 33),
    Numbers(numbers: 34),
    Numbers(numbers: 35),
    Numbers(numbers: 36),
    Numbers(numbers: 37),
    Numbers(numbers: 38),
    Numbers(numbers: 39),
    Numbers(numbers: 41),
    Numbers(numbers: 42),
    Numbers(numbers: 43),
    Numbers(numbers: 44),
    Numbers(numbers: 45),
    Numbers(numbers: 46),
    Numbers(numbers: 47),
    Numbers(numbers: 48),
    Numbers(numbers: 49),
    Numbers(numbers: 50),
  ];
}
